#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_FILE="${AI_ENV_FILE:-${ROOT_DIR}/.env.ai.local}"
OUTPUT_FILE="${AI_GATEWAY_ENV_FILE:-${ROOT_DIR}/.env.ai.gateway.local}"

if [[ $# -gt 0 ]]; then
  echo "Usage: $0" >&2
  exit 2
fi

if [[ ! -f "${SOURCE_FILE}" ]]; then
  echo "Missing AI environment file: ${SOURCE_FILE}" >&2
  echo "Copy .env.ai.example to .env.ai.local and configure it first." >&2
  exit 1
fi

python3 - "${SOURCE_FILE}" "${OUTPUT_FILE}" <<'PY'
from pathlib import Path
import os
import sys

source = Path(sys.argv[1])
output = Path(sys.argv[2])
allowed = (
    "MYAPP_AI_ORCHESTRATOR_URL",
    "MYAPP_AI_SERVICE_TOKEN",
    "MYAPP_AI_VECTOR_SEARCH_ENABLED",
    "MYAPP_AI_EMBEDDING_MODEL",
    "MYAPP_AI_QDRANT_COLLECTION",
    "MYAPP_AI_QDRANT_ALIAS",
    "MYAPP_AI_VECTOR_EXCLUDED_ITEM_PREFIXES",
    "MYAPP_AI_ENVIRONMENT",
    "MYAPP_AI_RETENTION_DAYS",
)
defaults = {
    "MYAPP_AI_ORCHESTRATOR_URL": "http://ai-orchestrator:4010",
    "MYAPP_AI_VECTOR_SEARCH_ENABLED": "0",
    "MYAPP_AI_QDRANT_COLLECTION": "myapp-products-v1",
    "MYAPP_AI_VECTOR_EXCLUDED_ITEM_PREFIXES": "HTTP-",
    "MYAPP_AI_ENVIRONMENT": "development",
    "MYAPP_AI_RETENTION_DAYS": "30",
}
required = {"MYAPP_AI_SERVICE_TOKEN"}

values: dict[str, str] = {}
for raw_line in source.read_text(encoding="utf-8").splitlines():
    line = raw_line.strip()
    if not line or line.startswith("#") or "=" not in line:
        continue
    key, value = line.split("=", 1)
    key = key.strip()
    if key not in allowed:
        continue
    if key in values:
        raise SystemExit(f"Duplicate {key} in {source}")
    values[key] = value.strip()

for key, value in defaults.items():
    values.setdefault(key, value)

missing = sorted(key for key in required if not values.get(key))
if missing:
    raise SystemExit(f"Missing required AI gateway variables in {source}: {', '.join(missing)}")

temporary = output.with_suffix(output.suffix + ".tmp")
temporary.write_text(
    "# Generated by sync-ai-gateway-env.sh; do not edit or commit.\n"
    + "\n".join(f"{key}={values[key]}" for key in allowed if key in values)
    + "\n",
    encoding="utf-8",
)
os.chmod(temporary, 0o600)
os.replace(temporary, output)
PY

chmod 600 "${OUTPUT_FILE}"
echo "Synchronized restricted AI gateway environment: ${OUTPUT_FILE}"
